/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrototypenRouteImport } from './routes/prototypen'
import { Route as DesignguidenRouteImport } from './routes/designguiden'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypenRoute = PrototypenRouteImport.update({
  id: '/prototypen',
  path: '/prototypen',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignguidenRoute = DesignguidenRouteImport.update({
  id: '/designguiden',
  path: '/designguiden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/designguiden': typeof DesignguidenRoute
  '/prototypen': typeof PrototypenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/designguiden': typeof DesignguidenRoute
  '/prototypen': typeof PrototypenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/designguiden': typeof DesignguidenRoute
  '/prototypen': typeof PrototypenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/designguiden' | '/prototypen' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/designguiden' | '/prototypen' | '/sitemap.xml'
  id: '__root__' | '/' | '/designguiden' | '/prototypen' | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignguidenRoute: typeof DesignguidenRoute
  PrototypenRoute: typeof PrototypenRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototypen': {
      id: '/prototypen'
      path: '/prototypen'
      fullPath: '/prototypen'
      preLoaderRoute: typeof PrototypenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designguiden': {
      id: '/designguiden'
      path: '/designguiden'
      fullPath: '/designguiden'
      preLoaderRoute: typeof DesignguidenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignguidenRoute: DesignguidenRoute,
  PrototypenRoute: PrototypenRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
