/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrototypenRouteImport } from './routes/prototypen'
import { Route as HvordanLaverManReturIFlexposRouteImport } from './routes/hvordan-laver-man-retur-i-flexpos'
import { Route as FlexposPengeskuffeAabnerIkkeRouteImport } from './routes/flexpos-pengeskuffe-aabner-ikke'
import { Route as FlexposOplaeringNyeMedarbejdereRouteImport } from './routes/flexpos-oplaering-nye-medarbejdere'
import { Route as DesignguidenRouteImport } from './routes/designguiden'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypenRoute = PrototypenRouteImport.update({
  id: '/prototypen',
  path: '/prototypen',
  getParentRoute: () => rootRouteImport,
} as any)
const HvordanLaverManReturIFlexposRoute =
  HvordanLaverManReturIFlexposRouteImport.update({
    id: '/hvordan-laver-man-retur-i-flexpos',
    path: '/hvordan-laver-man-retur-i-flexpos',
    getParentRoute: () => rootRouteImport,
  } as any)
const FlexposPengeskuffeAabnerIkkeRoute =
  FlexposPengeskuffeAabnerIkkeRouteImport.update({
    id: '/flexpos-pengeskuffe-aabner-ikke',
    path: '/flexpos-pengeskuffe-aabner-ikke',
    getParentRoute: () => rootRouteImport,
  } as any)
const FlexposOplaeringNyeMedarbejdereRoute =
  FlexposOplaeringNyeMedarbejdereRouteImport.update({
    id: '/flexpos-oplaering-nye-medarbejdere',
    path: '/flexpos-oplaering-nye-medarbejdere',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesignguidenRoute = DesignguidenRouteImport.update({
  id: '/designguiden',
  path: '/designguiden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/designguiden': typeof DesignguidenRoute
  '/flexpos-oplaering-nye-medarbejdere': typeof FlexposOplaeringNyeMedarbejdereRoute
  '/flexpos-pengeskuffe-aabner-ikke': typeof FlexposPengeskuffeAabnerIkkeRoute
  '/hvordan-laver-man-retur-i-flexpos': typeof HvordanLaverManReturIFlexposRoute
  '/prototypen': typeof PrototypenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/designguiden': typeof DesignguidenRoute
  '/flexpos-oplaering-nye-medarbejdere': typeof FlexposOplaeringNyeMedarbejdereRoute
  '/flexpos-pengeskuffe-aabner-ikke': typeof FlexposPengeskuffeAabnerIkkeRoute
  '/hvordan-laver-man-retur-i-flexpos': typeof HvordanLaverManReturIFlexposRoute
  '/prototypen': typeof PrototypenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/designguiden': typeof DesignguidenRoute
  '/flexpos-oplaering-nye-medarbejdere': typeof FlexposOplaeringNyeMedarbejdereRoute
  '/flexpos-pengeskuffe-aabner-ikke': typeof FlexposPengeskuffeAabnerIkkeRoute
  '/hvordan-laver-man-retur-i-flexpos': typeof HvordanLaverManReturIFlexposRoute
  '/prototypen': typeof PrototypenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/designguiden'
    | '/flexpos-oplaering-nye-medarbejdere'
    | '/flexpos-pengeskuffe-aabner-ikke'
    | '/hvordan-laver-man-retur-i-flexpos'
    | '/prototypen'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/designguiden'
    | '/flexpos-oplaering-nye-medarbejdere'
    | '/flexpos-pengeskuffe-aabner-ikke'
    | '/hvordan-laver-man-retur-i-flexpos'
    | '/prototypen'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/designguiden'
    | '/flexpos-oplaering-nye-medarbejdere'
    | '/flexpos-pengeskuffe-aabner-ikke'
    | '/hvordan-laver-man-retur-i-flexpos'
    | '/prototypen'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignguidenRoute: typeof DesignguidenRoute
  FlexposOplaeringNyeMedarbejdereRoute: typeof FlexposOplaeringNyeMedarbejdereRoute
  FlexposPengeskuffeAabnerIkkeRoute: typeof FlexposPengeskuffeAabnerIkkeRoute
  HvordanLaverManReturIFlexposRoute: typeof HvordanLaverManReturIFlexposRoute
  PrototypenRoute: typeof PrototypenRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototypen': {
      id: '/prototypen'
      path: '/prototypen'
      fullPath: '/prototypen'
      preLoaderRoute: typeof PrototypenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hvordan-laver-man-retur-i-flexpos': {
      id: '/hvordan-laver-man-retur-i-flexpos'
      path: '/hvordan-laver-man-retur-i-flexpos'
      fullPath: '/hvordan-laver-man-retur-i-flexpos'
      preLoaderRoute: typeof HvordanLaverManReturIFlexposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flexpos-pengeskuffe-aabner-ikke': {
      id: '/flexpos-pengeskuffe-aabner-ikke'
      path: '/flexpos-pengeskuffe-aabner-ikke'
      fullPath: '/flexpos-pengeskuffe-aabner-ikke'
      preLoaderRoute: typeof FlexposPengeskuffeAabnerIkkeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flexpos-oplaering-nye-medarbejdere': {
      id: '/flexpos-oplaering-nye-medarbejdere'
      path: '/flexpos-oplaering-nye-medarbejdere'
      fullPath: '/flexpos-oplaering-nye-medarbejdere'
      preLoaderRoute: typeof FlexposOplaeringNyeMedarbejdereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designguiden': {
      id: '/designguiden'
      path: '/designguiden'
      fullPath: '/designguiden'
      preLoaderRoute: typeof DesignguidenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignguidenRoute: DesignguidenRoute,
  FlexposOplaeringNyeMedarbejdereRoute: FlexposOplaeringNyeMedarbejdereRoute,
  FlexposPengeskuffeAabnerIkkeRoute: FlexposPengeskuffeAabnerIkkeRoute,
  HvordanLaverManReturIFlexposRoute: HvordanLaverManReturIFlexposRoute,
  PrototypenRoute: PrototypenRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
